# Back End Deployment Values
deployment_back:
  name: alco24back
  port: 5003

containers_back:
  image: 453465607768.dkr.ecr.us-east-1.amazonaws.com/alcodostavka24-back-repo
  tag: "1.0.0"
  imagePullPolicy: Always

resources_back:
  limits:
    cpu: 256m
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 128Mi

# Back End Service Values
service_back:
  name: alco24backsvc
  ports:
    - port: 5003
      targetPort: 5003

      # Config Map Values
ConfigMap:
  name: alco24back-config
config:
  NODE_ENV: 'dev'
  APP_PORT: '5003'
  JWT_KEY: 'my-jwt-key-4545'
  JWT_ID: 'myjwtid'
  JWT_ALGORITHM: 'sha265'
  JWT_EXPIRATION: '3d'
  TOKEN_SECRET: 'jwtsecretforall'
  ACCESSTOKEN_SECRET: 'jwtsecret'
  REFRESH_TOKEN_SECRET: 'secret refresh token definition'
  REFRESH_TOKEN_EXPIRATION: '7d'
  DB_TYPE: 'postgres'
  DB_HOST: 'alco24dbsvc'
  DB_PORT: '5432'
  DB_USERNAME: 'db_admin'
  DB_PASSWORD: 'postgre'
  DB_NAME: 'db_expensive'